version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15-alpine3.17
    ports:
      - "5433:5432" # Mapeia a porta 5433 do host para a porta 5432 no container
    user: postgres
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_DB: orbis
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 2
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    working_dir: /app
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/orbis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  db_data:
